version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "nth-check"
        versions: ["<2.0.1"]
      - dependency-name: "postcss"
        versions: ["<8.4.31"]
    commit-message:
      prefix: "deps"
    open-pull-requests-limit: 10