name: Deploy Website with Environment Variables

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version

      # Step to load environment variables from .env file
      - name: Load environment variables from .env file
        uses: falti/dotenv-action@v1.1.4
        with:
          path: .env  # Path to your .env file

      # Show environment variables (optional, for debugging)
      - name: Show environment variables
        run: |
          echo "Supabase URL: $SUPABASE_URL"
          echo "Supabase Key: $SUPABASE_KEY"

      # Install Netlify CLI and authenticate using the API token
      - name: Install Netlify CLI
        run: |
          npm install -g netlify-cli

      - name: Authenticate with Netlify
        run: |
          echo ${{ secrets.NETLIFY_AUTH_TOKEN }} | netlify login --auth nfp_PeV9WB5JXjGQeqLDpWR4xWxummL1JMb60966

      # Deploy to Netlify
      - name: Deploy to Netlify
        run: |
          netlify link
          netlify deploy --prod --dir=build  # Adjust the `--dir` argument based on your build output
