name: Deploy Website with Environment Variables

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Load environment variables from .env file
        uses: falti/dotenv-action@v1.1.4
        with:
          path: .env

      - name: Show environment variables
        run: |
          echo "Supabase URL: $SUPABASE_URL"
          echo "Supabase Key: $SUPABASE_KEY"

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Check and initialize package.json
        run: |
          if [ ! -f package.json ]; then
            echo "package.json not found. Initializing..."
            npm init -y
            # Add a default "build" script to avoid errors
            npm set-script build "echo 'No build step needed'"
          else
            echo "package.json already exists."
          fi

      # Skip the build process if it's not needed
      - name: Install dependencies and run build
        run: |
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .  # Adjust this directory if needed
