name: Deploy Website with Environment Variables

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to use the latest version

      # Step to load environment variables from .env file
      - name: Load environment variables from .env file
        uses: falti/dotenv-action@v1.1.4
        with:
          path: .env  # Corrected input parameter for the .env file path

      - name: Show environment variables (optional)
        run: |
          echo "Supabase URL: $SUPABASE_URL"
          echo "Supabase Key: $SUPABASE_KEY"

      # You can add a step to deploy your website to your hosting service
      - name: Deploy to Netlify or other service
        run: |
          # Your deploy command here (for example, with Netlify CLI or similar service)
          netlify deploy --prod
